nelmio_cors:
  defaults:
      allow_origin: ['*']
      allow_headers: ['*']
      allow_methods: ['POST', 'GET', 'PATCH', 'DELETE']
      max_age: 3600
      hosts: ['']
  paths:
    '^/':
      allow_origin: ['*']
      allow_headers: ['*']
      allow_methods: ['POST', 'GET', 'PATCH', 'DELETE']
      max_age: 3600
      hosts: ['']
